### ISSUE TITLE
"sample_cfg.yml" link unused on page "contiv.github.io/install/netplugin/install.html"

### ISSUE THREAD

**Issue by gwanii** [contiv/contiv.github.io#10]
When open the url "http://contiv.github.io/install/netplugin/extras/sample_cfg.yml ", browser tells me "Page Not Found".

**Comment by dawelsch** [comment]
In pull request #14, files now have their own home on the new website, /extras. Should not see broken links to sample files anymore.

**Comment by stacykor** [comment]
Resolved. Closing.
