### ISSUE TITLE
problem with multi host networking tutorial

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/contiv.github.io#141]
[vagrant@contiv-node3 ~]$ docker run -itd --name=contiv-c1 --net=contiv-net -e constraint:node=contiv-node3 alpine /bin/sh
docker: Error response from daemon: Unable to find a node that satisfies the following conditions
[available container slots].
See 'docker run --help'.

**Comment by gaurav-dalvi** [comment]
@rhim

**Comment by gaurav-dalvi** [comment]
Wrong command
`docker run -itd --name=contiv-c2 --net=contiv-net -e constraint:node=contiv-node4 alpine /bin/sh`

Correct command
`docker run -itd --name=contiv-c2 --net=contiv-net -e constraint:node==contiv-node4 alpine /bin/sh`

**Comment by rhim** [comment]
LGTM. Go ahead and merge.

-Himanshu

On May 8, 2017, at 2:59 PM, Gaurav Dalvi <notifications@github.com<mailto:notifications@github.com>> wrote:


Wrong command
docker run -itd --name=contiv-c2 --net=contiv-net -e constraint:node=contiv-node4 alpine /bin/sh

Correct command
docker run -itd --name=contiv-c2 --net=contiv-net -e constraint:node==contiv-node4 alpine /bin/sh

-

**Comment by gaurav-dalvi** [comment]
This is committed.
