### ISSUE TITLE
Invalid GitHub URLs under "Known issues" in Release Notes for 1.1

### ISSUE THREAD

**Issue by arrowfoot** [contiv/contiv.github.io#159]
The "Known issues" section in the Release Notes for Contiv 1.1 contains URLs pointing to a non-existent or hidden GitHub repo: https://github.com/contiv/ccn/issues/380, https://github.com/contiv/ccn/issues/383

**Comment by dseevr** [comment]
Thanks for the report.  These were removed in https://github.com/contiv/contiv.github.io/pull/161
