### ISSUE TITLE
Is service load balancing demo correct?

### ISSUE THREAD

**Issue by dawelsch** [contiv/contiv.github.io#16]
In the discussion of service load balancing (documents/networking/services.md): first part of example creates a network 'contiv-srv-net' with a set of labels. Second part creates a network 'contiv-net' with no labels and attaches labeled service containers to that network. This doesn't seem to make sense. Are the two examples supposed to be related? What's the correct sequence of commands?

**Comment by stacykor** [comment]
No longer applicable.
