### ISSUE TITLE
Swarm port needs to be changed at doc site

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/contiv.github.io#43]
http://contiv.github.io/documents/gettingStarted/networking/swarm.html

Here instead of `export DOCKER_HOST=tcp://192.168.2.10:2375`

now it should be `export DOCKER_HOST=tcp://192.168.2.10:3375` as we are using docker 1.12 now.

**Comment by gaurav-dalvi** [comment]
@gkvijay : Could you please quickly do this ? As It is related to your swarm fix in netplugin repo

**Comment by gaurav-dalvi** [comment]
Also please see if there is anything wrong with this entire swarm page.

**Comment by stacykor** [comment]
Swarm install step was updated.

**Comment by stacykor** [comment]
@gaurav-dalvi  okay to close?

**Comment by gaurav-dalvi** [comment]
Yes ok  to close.

**Comment by stacykor** [comment]
Closing.
