### ISSUE TITLE
Reduce font size for tutorials

### ISSUE THREAD

**Issue by stacykor** [contiv/contiv.github.io#54]
Per Rohit reduce font size for tutorials

**Comment by akamkar** [comment]
The font on the homepage needs some adjustments as well. 
![image](https://cloud.githubusercontent.com/assets/18014543/22959811/ffe79f14-f2ed-11e6-86b9-b510d4173912.png)

**Comment by stacykor** [comment]
![screen shot 2017-02-15 at 10 02 59 am](https://cloud.githubusercontent.com/assets/4722362/22988583/77f9f0e6-f367-11e6-9c1a-8c4f9083d64b.png)

Looks good now, thanks!
