### ISSUE TITLE
consistent Size of fonts

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/contiv.github.io#56]
![screen shot 2017-02-14 at 8 07 09 pm](https://cloud.githubusercontent.com/assets/2373663/22960278/46d4c6ba-f2f1-11e6-8b4a-8ca8f1d9c072.png)

Different font sizes here.

**Comment by stacykor** [comment]
![screen shot 2017-02-15 at 9 41 08 am](https://cloud.githubusercontent.com/assets/4722362/22987243/f1d2c17c-f362-11e6-8cdb-c54a98a21ef7.png)
