### ISSUE TITLE
Remove redundant buttons from API docs 

### ISSUE THREAD

**Issue by yuva29** [contiv/contiv.github.io#62]
Here both `GET` gives the same information. Do we need this redundant buttons ? Also, this occupies extra space. Its better to remove the section that's displayed when the API link is clicked. 

<img width="860" alt="screen shot 2017-02-15 at 10 43 31 am" src="https://cloud.githubusercontent.com/assets/11082310/22989878/4d766ee4-f36c-11e6-91ac-035d48f0b929.png">

**Comment by dseevr** [comment]
Fixed by https://github.com/contiv/contivmodel/commit/56e739a3ae64e8c5ff401039d95b1074d974e86a
