### ISSUE TITLE
Image with borders in the home page

### ISSUE THREAD

**Issue by yuva29** [contiv/contiv.github.io#66]
Current image is plain on both bottom and right sides. Can we use some image with borders on all sides in the home page so, it kind of isolates the image from other contents ?
@stacykor @akamkar  What do you think? 

<img width="811" alt="screen shot 2017-02-15 at 12 08 19 pm" src="https://cloud.githubusercontent.com/assets/11082310/22993367/9cb256f2-f377-11e6-9233-a23aac8c2686.png">

**Comment by akamkar** [comment]
Let me know if you need help. I can create one with a nice shadow.

**Comment by stacykor** [comment]
That would be great. This is what I have so far and I'm not thrilled. 

![createnetwork2-45e97f3f](https://cloud.githubusercontent.com/assets/4722362/22996850/0bf7a2bc-f385-11e6-8982-e9b320675ee1.png)

**Comment by akamkar** [comment]
![createnetwork-2-226eb853](https://cloud.githubusercontent.com/assets/18014543/22998059/fd8f7916-f389-11e6-9d46-6e8ec46feba1.png)

**Comment by akamkar** [comment]
![createnetwork-3](https://cloud.githubusercontent.com/assets/18014543/22998569/39789bea-f38c-11e6-9d8f-89f4a71feafd.png)

**Comment by akamkar** [comment]
Here are two options.

**Comment by stacykor** [comment]
Thanks @akamkar, showed it to Amit and Rohit and went with option 1:

http://contiv.github.io/
