### ISSUE TITLE
Suggestion: Make `Contiv` font bold and bigger

### ISSUE THREAD

**Issue by yuva29** [contiv/contiv.github.io#67]
Contiv has the same font size as other items on this bar. Can we just make it little bigger and bold?  

<img width="980" alt="screen shot 2017-02-15 at 12 16 23 pm" src="https://cloud.githubusercontent.com/assets/11082310/22993692/b9f603fc-f378-11e6-9b59-1dbb5922fbb0.png">

Also, can we add a logo as well there? something like https://kubernetes.io/docs/

@stacykor whatever you think is the best.

**Comment by stacykor** [comment]
![screen shot 2017-03-09 at 10 09 15 am](https://cloud.githubusercontent.com/assets/4722362/23763953/9033e32e-04b0-11e7-8e8a-3f3f1406c673.png)

**Comment by stacykor** [comment]
We've added a bright Contiv Logo to replace it, making it more consistent with the other sites using this style.
