### ISSUE TITLE
2 big blue section colors vary slightly 

### ISSUE THREAD

**Issue by yuva29** [contiv/contiv.github.io#70]
Blue sections in homepage http://contiv.github.io vary slightly. Is it expected ?

**Comment by akamkar** [comment]
Yes, I noticed that too. I think it would be best to use only one blue or use entirely different color for the icons and box on the bottom of the page.

**Comment by stacykor** [comment]
Everything is cobalt except for the bottom section which was kubernetes blue. I've changed it to black:

http://contiv.github.io/

I'm open to other colors. Grey was rejected twice.
