### ISSUE TITLE
Spacing differs across sections in left pane

### ISSUE THREAD

**Issue by yuva29** [contiv/contiv.github.io#72]
Spacing between the rows in `reference` section is much more than other sections. Please ignore if its not a big deal.
<img width="290" alt="screen shot 2017-02-15 at 2 10 46 pm" src="https://cloud.githubusercontent.com/assets/11082310/22997777/a8034de8-f388-11e6-915c-8963ff806fbf.png">

**Comment by stacykor** [comment]
![screen shot 2017-02-16 at 11 16 53 am](https://cloud.githubusercontent.com/assets/4722362/23036982/9d4eaef4-f439-11e6-9a0e-7b4c7f0856f4.png)

hidden <br> tags removed.
