### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by akamkar** [contiv/contiv.github.io#76]
![Uploading Screen Shot 2017-02-16 at 9.22.57 AM.png…]()
![screen shot 2017-02-16 at 8 55 30 am](https://cloud.githubusercontent.com/assets/18014543/23032635/ed72be30-f429-11e6-8ef9-f05681c2a03a.png)

**Comment by akamkar** [comment]
<img width="1213" alt="screen shot 2017-02-16 at 9 22 57 am" src="https://cloud.githubusercontent.com/assets/18014543/23037090/fe0ed552-f439-11e6-9c13-68ac3b11be21.png">

**Comment by stacykor** [comment]
These files have been updated. 

http://contiv.github.io/documents/admin/manageUsers.html

http://contiv.github.io/documents/admin/createNodes.html

Thanks for the catch!
